### ISSUE TITLE
pull error

### ISSUE THREAD

**Issue by superfan321** [cmu-sei/GHOSTS-ANIMATOR#14]
Hoping this project is still active, have used it before and love it. 

I am recieving this error using the .yml file 

"ERROR: manifest for dustinupdyke/ghosts-animator:0.8.0 not found: manifest unknown: manifest unknown"

or when trying to pull straight from docker I get this 

ERROR: manifest for dustinupdyke/ghosts-animator:latest not found: manifest unknown: manifest unknown

**Comment by sei-dupdyke** [comment]
Definitely still active ;) 

I just pushed this container, sorry for the confusion. Should work now..
