### ISSUE TITLE
Pull access denied for ghosts/animator

### ISSUE THREAD

**Issue by b33kar** [cmu-sei/GHOSTS-ANIMATOR#3]
Is this project still viable? Getting the following error when running docker-compose up -d:

Error response from daemon: pull access denied for ghosts/animator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Thanks!

**Comment by sei-dupdyke** [comment]
Hi sorry, I am just seeing this. Yes, this project is still active.

There was a typo in the compose file, I just corrected it - basically, it was pulling an invalid image name for Animator. Should be good to go now, sorry about that.

**Comment by b33kar** [comment]
Thanks! It's working well now.
